export enum WebhookState {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  ERROR = 'ERROR',
}

export enum WebhookType {
  GITHUB = 'GITHUB',
  GITLAB = 'GITLAB',
  DISCOURSE = 'DISCOURSE',
  GROUPSIO = 'GROUPSIO',
  CROWD_GENERATED = 'CROWD_GENERATED',
}
