import { generateUUIDv1 } from '@crowd/common'
import { insertSegments } from '@crowd/data-access-layer'
import type { QueryExecutor } from '@crowd/database'
import { type SegmentDbInsert, type SegmentDbRow, SegmentStatus } from '@crowd/types'

import { withDefaults } from './defaults'

/** Hierarchy fields are derived by createSegments; callers must supply name + slug. */
type SegmentNodeInput = {
  name: string
  slug: string
} & Partial<
  Omit<
    SegmentDbInsert,
    | 'name'
    | 'slug'
    | 'parentId'
    | 'grandparentId'
    | 'parentSlug'
    | 'grandparentSlug'
    | 'parentName'
    | 'grandparentName'
  >
>

export type CreateSubproject = SegmentNodeInput
export type CreateProject = SegmentNodeInput & {
  subprojects?: CreateSubproject[]
}
export type CreateProjectGroup = SegmentNodeInput & {
  projects?: CreateProject[]
}

export type CreateSegmentsResult = {
  projectGroups: Array<{
    row: SegmentDbRow
    projects: Array<{
      row: SegmentDbRow
      subprojects: SegmentDbRow[]
    }>
  }>
}

const applySegmentNodeDefaults = withDefaults<SegmentNodeInput>()({
  id: () => generateUUIDv1(),
  status: SegmentStatus.ACTIVE,
  isLF: true,
})

/**
 * Fills missing allowlisted fields on each node. Does not invent children.
 * Caller still owns name, slug, and tree shape. Explicit values always win.
 */
export function withSegmentDefaults(trees: CreateProjectGroup[]): CreateProjectGroup[] {
  return trees.map((group) => {
    const { projects, ...groupFields } = group
    const [projectGroup] = applySegmentNodeDefaults([groupFields])

    return {
      ...projectGroup,
      projects: projects?.map((project) => {
        const { subprojects, ...projectFields } = project
        const [projectDefaults] = applySegmentNodeDefaults([projectFields])

        return {
          ...projectDefaults,
          subprojects: subprojects ? applySegmentNodeDefaults(subprojects) : subprojects,
        }
      }),
    }
  })
}

/**
 * Inserts nested segment trees in one go. Derives parent/grandparent fields from
 * structure (`type` is generated by the DB from parentSlug/grandparentSlug).
 * Requires name + slug on every node.
 */
export async function createSegments(
  qx: QueryExecutor,
  trees: CreateProjectGroup[],
): Promise<CreateSegmentsResult> {
  const rowsToInsert: SegmentDbInsert[] = []
  const structure: Array<{
    projectGroupId: string
    projects: Array<{ projectId: string; subprojectIds: string[] }>
  }> = []

  for (const group of trees) {
    const { projects: groupProjects = [], ...groupFields } = group
    const projectGroupId = groupFields.id ?? generateUUIDv1()
    const projectGroupName = groupFields.name
    const projectGroupSlug = groupFields.slug

    rowsToInsert.push({
      ...groupFields,
      id: projectGroupId,
      name: projectGroupName,
      slug: projectGroupSlug,
      parentId: null,
      parentSlug: null,
      parentName: null,
      grandparentId: null,
      grandparentSlug: null,
      grandparentName: null,
    })

    const projectStructs: Array<{ projectId: string; subprojectIds: string[] }> = []

    for (const project of groupProjects) {
      const { subprojects: projectSubprojects = [], ...projectFields } = project
      const projectId = projectFields.id ?? generateUUIDv1()
      const projectName = projectFields.name
      const projectSlug = projectFields.slug

      rowsToInsert.push({
        ...projectFields,
        id: projectId,
        name: projectName,
        slug: projectSlug,
        parentId: projectGroupId,
        parentSlug: projectGroupSlug,
        parentName: projectGroupName,
        grandparentId: null,
        grandparentSlug: null,
        grandparentName: null,
      })

      const subprojectIds: string[] = []

      for (const subproject of projectSubprojects) {
        const subprojectId = subproject.id ?? generateUUIDv1()
        const subprojectName = subproject.name
        const subprojectSlug = subproject.slug

        rowsToInsert.push({
          ...subproject,
          id: subprojectId,
          name: subprojectName,
          slug: subprojectSlug,
          parentId: projectId,
          parentSlug: projectSlug,
          parentName: projectName,
          grandparentId: projectGroupId,
          grandparentSlug: projectGroupSlug,
          grandparentName: projectGroupName,
        })

        subprojectIds.push(subprojectId)
      }

      projectStructs.push({ projectId, subprojectIds })
    }

    structure.push({ projectGroupId, projects: projectStructs })
  }

  const rows = await insertSegments(qx, rowsToInsert, true, true)
  const byId = new Map(rows.map((row) => [row.id, row]))

  const requireRow = (id: string): SegmentDbRow => {
    const row = byId.get(id)
    if (!row) {
      throw new Error(`createSegments: inserted segment ${id} was not returned`)
    }
    return row
  }

  return {
    projectGroups: structure.map((group) => ({
      row: requireRow(group.projectGroupId),
      projects: group.projects.map((project) => ({
        row: requireRow(project.projectId),
        subprojects: project.subprojectIds.map((id) => requireRow(id)),
      })),
    })),
  }
}
