FROM node:24-alpine as builder

RUN apk add --no-cache python3 make g++

WORKDIR /usr/crowd/app
COPY ./package.json ./pnpm-workspace.yaml ./pnpm-lock.yaml ./
RUN corepack enable && corepack prepare --activate
RUN pnpm fetch

COPY ./services ./services
RUN pnpm i --frozen-lockfile

FROM node:24-alpine as runner

WORKDIR /usr/crowd/app
ENV pnpm_config_verifyDepsBeforeRun=false
COPY ./package.json ./
RUN corepack enable && corepack prepare --activate

COPY --from=builder /usr/crowd/app/node_modules ./node_modules
COPY --from=builder /usr/crowd/app/services/base.tsconfig.json ./services/base.tsconfig.json
COPY --from=builder /usr/crowd/app/services/libs ./services/libs
COPY --from=builder /usr/crowd/app/services/apps/webhook_api/ ./services/apps/webhook_api
