#!/usr/bin/env bash

if [[ ${TERM} == "" || ${TERM} == "dumb" ]]; then
    RED=""
    GREEN=""
    GREY=""
    YELLOW=""
    RESET=""
else
    RED=`tput setaf 1`
    GREEN=`tput setaf 2`
    GREY=`tput setaf 7`
    YELLOW=`tput setaf 3`
    RESET=`tput sgr0`
fi

USER_NAME=`whoami`

yell () {
    printf "${YELLOW}%s\n${RESET}" "$1"
}

say () {
    printf "${GREEN}%s\n${RESET}" "$1"
}

whisper () {
    printf "${GREY}%s\n${RESET}" "$1"
}

error () {
    printf "${RED}%s\n${RESET}" "$1"
}

progress () {
    printf "  > %s\n" "$1"
}

nl () {
    printf "\n"
}
